class TestDateTimePartition:  # TODO: copy and modify from timepartition_test.py
    def test_affine_transform(self): ...

    def test_contains(self): ...

    def test_days(self): ...

    def test_dunder_bool(self): ...

    def test_dunder_contains(self): ...

    def test_dunder_eq(self): ...

    def test_dunder_init(self): ...

    def test_eclipse_backward(self): ...

    def test_eclipse_forward(self): ...

    def test_end(self): ...

    def test_ends(self): ...

    def test_from_minutes_and_end(self): ...

    def test_from_minutes_and_start(self): ...

    def test_from_partition(self): ...

    def test_from_relative_lengths(self): ...

    def test_gap(self): ...

    def test_hours(self): ...

    def test_hull(self): ...

    def test_interior_point(self): ...

    def test_intersection(self): ...

    def test_midpoint(self): ...

    def test_minutes(self): ...

    def test_passes_day_boundary(self): ...

    def test_reordered(self): ...

    def test_resolve_gaps(self): ...

    def test_resolve_overlaps(self): ...

    def test_seconds(self): ...

    def test_shift_end_rigid(self): ...

    def test_shift_start_rigid(self): ...

    def test_snap_end_to(self): ...

    def test_snap_start_to(self): ...

    def test_spans(self): ...

    def test_split(self): ...

    def test_squeeze_with_rollover(self): ...

    def test_squeeze(self): ...

    def test_stack(self): ...

    def test_start(self): ...

    def test_starts(self): ...
